In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving tips.csv to tips.csv

In [5]:
df = pd.read_csv('tips.csv')
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

## Apply On Single Colum

In [6]:
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15
..          ...   ...     ...    ...   ...     ...   ...               ...
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39

             Payer Name         CC Number Payment ID
0    Christy Cunningham  3560325168603410    Sun2959
1        Douglas Tucker  4478071379779230    Sun4608
2        Travis Walters  6011812112971322    Sun4458
3      Nathaniel Harris  4676137647685994    Sun5260
4          Tonya Carter  4832732618637221    Sun2251
..                  ...               ...        ...
239       Michael Avila  5296068606052842    Sat2657
240      Monica Sanders  3506806155565404    Sat1766
241          Keith Wong  6011891618747196    Sat3880
242        Dennis Dixon     4375220550950      Sat17
243     Michelle Hardin  3511451626698139    Thur672

[244 rows x 11 columns]>

In [7]:
str(123456789)[-4:]

'6789'

In [8]:
def  last_four(num):
  return str(num)[-4:]

In [9]:
last_four(123456789)

'6789'

In [11]:
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [13]:
df['total_bill'].mean()

np.float64(19.78594262295082)

In [15]:
def yelp(price):
   if price<10:
      return  '$'
   elif price>=10  and  price<30:
      return  '$$'
   else:
      return '$$$'

In [16]:
df['yelp']  = df['total_bill'].apply(yelp)

In [18]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,$$

In [19]:
def simple(num):
  return num*2

In [20]:
simple(2)

4

In [21]:
lambda num: num  *2

In [22]:
df['total_bill'].apply(simple)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

##With  Lambda

In [24]:
df['total_bill'].apply(lambda bill:  bill  *2)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [26]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$

In [27]:
def getQuality(total_bill, tip):
  if tip/total_bill > 0.25:
    return "Generous"
  else:
    return "Other"

In [28]:
getQuality(16.99, 1.01)

'Other'

In [29]:
df[['total_bill','tip']].apply(lambda df: getQuality(df['total_bill'], df['tip']), axis=1)

0      Other
1      Other
2      Other
3      Other
4      Other
       ...
239    Other
240    Other
241    Other
242    Other
243    Other
Length: 244, dtype: object

In [33]:
df['Quality'] = np.vectorize(getQuality)(df['total_bill'], df['tip'])
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,yelp,Quality
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$,Other
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$,Other
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$,Other
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$,Other
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$,Other